"""
Django settings for trufit_backend project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ox_%gpzf=jy^3jp-6atrs_ncek47inxcc&+a-2+j%sx(f!szxk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

#ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".onrender.com", ".vercel.app", "localhost:5173"]
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")
 
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
AUTH_USER_MODEL = 'admin_functions.User'
CORS_ALLOWED_ORIGINS = [
    "https://tru-fit.vercel.app",
    # add others if needed:
    # "http://localhost:3000",
]

#print(CORS_ALLOWED_ORIGINS, "=================CORS===================")
# If you want to allow all origins (not recommended for production):
CORS_ALLOW_ALL_ORIGINS = False
# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'admin_functions',
    'storages',
    
    
    
]


AUTHENTICATION_BACKENDS = (
      # Facebook OAuth backend
    'django.contrib.auth.backends.ModelBackend',  # Default backend
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "20/min",
        "user": "100/min",
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trufit_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = "trufit_backend.asgi.application"
WSGI_APPLICATION = 'trufit_backend.wsgi.application'



# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


import os
import dj_database_url



ENV = os.getenv("DJANGO_ENV", "dev")

if ENV == "prod":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("AWS_DB_NAME"),
            'USER': os.getenv("AWS_DB_USER"),
            'PASSWORD': os.getenv("AWS_DB_PASSWORD"),
            'HOST': os.getenv("AWS_DB_HOST"),
            'PORT': os.getenv("AWS_DB_PORT", "5432"),
            'CONN_MAX_AGE': 600,
            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get("DATABASE_URL"),
            conn_max_age=600,
            ssl_require=False
        )
    }

#print("Database Configured:", DATABASES['default'])

from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}
#DATABASES["default"]["CONN_MAX_AGE"] = 60
#DATABASES["default"]["CONN_HEALTH_CHECKS"] = True  # Django 4+

REDIS_URL = os.getenv("REDIS_URL") 
#REDIS_URL = "redis://:trustrongfitpass@13.233.100.193:6379/2"
#print(REDIS_URL) # e.g. redis://:pass@host:6379/0

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [os.getenv("REDIS_URL")]},
    }
} 
import os
from urllib.parse import urlparse


def with_db(url: str, db: int) -> str:
    """
    Take redis://.../<db> and return the same with a different db.
    If someone passed a URL without a trailing '/db', we still add it.
    """
    parsed = urlparse(url)
    # Ensure path like '/0' exists, then replace with the new db
    path = f"/{db}"
    return f"{parsed.scheme}://{parsed.netloc}{path}"

CACHE_REDIS_URL   = with_db(REDIS_URL, 1)       # /1
CELERY_BROKER_URL = with_db(REDIS_URL, 2)    
#print(CELERY_BROKER_URL, "============URL===============")   # /2
CELERY_RESULT_URL = with_db(REDIS_URL, 3) 

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_CACHE_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # Optional: safer serialization & socket timeouts
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
            "CONNECTION_POOL_KWARGS": {"max_connections": 50},
            "PARSER_CLASS": "redis.connection.HiredisParser",
            "SOCKET_CONNECT_TIMEOUT": 2,  # seconds
            "SOCKET_TIMEOUT": 2,
        },
        "KEY_PREFIX": "trufit",
        "TIMEOUT": 60 * 15,  # 15 minutes default cache TTL
    }
}



CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": CACHE_REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # Safer pool + timeouts (optional but recommended)
            "CONNECTION_POOL_KWARGS": {"max_connections": 50},
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
            "PARSER_CLASS": "redis.connection.HiredisParser",
            "SOCKET_CONNECT_TIMEOUT": 2,
            "SOCKET_TIMEOUT": 2,
        },
        "KEY_PREFIX": "trufit",
        "TIMEOUT": 60 * 15,  # 15 minutes default TTL
    }
}

# --------------------------
# Celery
# --------------------------
CELERY_BROKER_URL = CELERY_BROKER_URL
CELERY_RESULT_BACKEND = CELERY_RESULT_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Kolkata"

# IMPORTANT: disable eager for real workers/beat
CELERY_TASK_ALWAYS_EAGER = False


#CELERY_IMPORTS = ('authentication.tasks',)
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


EMAIL_HOST="smtp.gmail.com"
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER="abishek.reddy.020502@gmail.com"
EMAIL_HOST_PASSWORD="gwmktikhdvgncsuv"

import os

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LOGGING = {
  "version": 1, "disable_existing_loggers": False,
  "handlers": {"console": {"class": "logging.StreamHandler"}},
  "loggers": {
    "channels": {"handlers": ["console"], "level": "INFO"},
    "channels_redis": {"handlers": ["console"], "level": "INFO"},
    "ws": {"handlers": ["console"], "level": "INFO"},
  },
}


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_S3_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_REGION", "ap-south-1")
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"

# CRITICAL: don't send ACLs when uploading
AWS_DEFAULT_ACL = None

# Optional but useful
AWS_QUERYSTRING_AUTH = False
AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")

# Use S3 for static & media (adjust module path)
STATICFILES_STORAGE = "trufit_backend.storages.StaticRootS3Boto3Storage"
DEFAULT_FILE_STORAGE = "trufit_backend.storages.MediaRootS3Boto3Storage"

STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
MEDIA_URL  = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")

CASHFREE_APP_ID = os.getenv("CASHFREE_APP_ID")
CASHFREE_SECRET_KEY = os.getenv("CASHFREE_SECRET_KEY")


EMAIL_BACKEND = 'django_ses.SESBackend'

#EMAIL_HOST = "email-smtp.ap-south-1.amazonaws.com"  # your region
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True

#EMAIL_HOST_USER = os.environ.get("SES_SMTP_USER")       # from SES SMTP creds
#EMAIL_HOST_PASSWORD = os.environ.get("SES_SMTP_PASS")

AWS_SES_ACCESS_KEY_ID = os.getenv("AWS_SES_ACCESS_KEY_ID")
AWS_SES_SECRET_ACCESS_KEY = os.getenv("AWS_SES_SECRET_ACCESS_KEY")
AWS_SES_REGION_NAME = os.getenv("AWS_SES_REGION_NAME", "ap-south-1")
AWS_SES_REGION_ENDPOINT = f"email.{AWS_SES_REGION_NAME}.amazonaws.com"

DEFAULT_FROM_EMAIL = "abishek.129.203@gmail.com"


  # must be the verified email
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]