# Generated by Django 4.2.20 on 2025-08-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
