# Generated by Django 4.2.20 on 2025-08-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='CoachProfile/')),
                ('experience', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coach_level', models.CharField(choices=[('junior', 'JUNIOR'), ('midlevel', 'MIDLEVEL'), ('elite', 'ELITE')], max_length=13)),
            ],
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial_images/'),
        ),
    ]
