# Generated by Django 4.2.20 on 2025-08-21 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0004_coachprofile_alter_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='bullet_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='calendly_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='CoachCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=100)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='admin_functions.coachprofile')),
            ],
        ),
    ]
