# Generated by Django 4.2.20 on 2025-08-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0005_coachprofile_bio_coachprofile_bullet_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='coach_level',
            field=models.CharField(choices=[('junior', 'JUNIOR'), ('mid', 'MID'), ('elite', 'ELITE')], max_length=13),
        ),
    ]
