# Generated by Django 4.2.20 on 2025-08-21 08:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0006_alter_coachprofile_coach_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Enter a valid phone number.')])),
                ('residence', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(choices=[('razorpay', 'RAZORPAY'), ('cashfree', 'CASHFREE')], max_length=20)),
                ('plan', models.PositiveSmallIntegerField(choices=[(3, '3 MONTHS'), (6, '6 MONTHS')])),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='admin_functions.coachprofile')),
            ],
        ),
    ]
