# Generated by Django 4.2.20 on 2025-08-21 09:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0007_clientdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('junior', 'JUNIOR'), ('senior', 'SENIOR'), ('elite', 'ELITE')], max_length=12)),
                ('location', models.CharField(choices=[('domestic', 'DOMESTIC'), ('international', 'INTERNATIONAL')], max_length=20)),
                ('short_term_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('long_term_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('consultation_call_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='coach_level',
            field=models.CharField(choices=[('junior', 'JUNIOR'), ('senior', 'senior'), ('elite', 'ELITE')], max_length=13),
        ),
        migrations.AddConstraint(
            model_name='plans',
            constraint=models.UniqueConstraint(fields=('category', 'location'), name='uniq_plan_category_location'),
        ),
    ]
