# Generated by Django 4.2.20 on 2025-08-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0008_plans_alter_coachprofile_coach_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='intensity_level',
            field=models.IntegerField(choices=[(1, 'Not intense'), (2, 'A little intense'), (3, 'Somewhat intense'), (4, 'Intense'), (5, 'Very intense')], default=3),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='personality_traits',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='specialties',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='coach_level',
            field=models.CharField(choices=[('junior', 'JUNIOR'), ('senior', 'SENIOR'), ('elite', 'ELITE')], max_length=13),
        ),
    ]
