# Generated by Django 4.2.20 on 2025-08-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0009_coachprofile_gender_coachprofile_intensity_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachprofile',
            old_name='bullet_points',
            new_name='approach',
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='previous_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='specializations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='tags',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
