# Generated by Django 4.2.20 on 2025-08-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0011_alter_coachprofile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
