# Generated by Django 4.2.20 on 2025-08-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0012_coachprofile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='age',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='tags',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
