# Generated by Django 4.2.20 on 2025-08-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0013_testimonial_age_testimonial_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
