# Generated by Django 4.2.20 on 2025-08-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0014_alter_testimonial_age_alter_testimonial_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
