# Generated by Django 4.2.20 on 2025-08-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0015_blog_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=100),
        ),
    ]
