# Generated by Django 4.2.20 on 2025-08-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0016_clientdetails_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='plan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CALL'), (12, '12 WEEKS'), (24, '24 WEEKS')]),
        ),
    ]
