# Generated by Django 4.2.20 on 2025-08-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0017_alter_clientdetails_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='plan',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
