# Generated by Django 4.2.20 on 2025-09-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0018_alter_clientdetails_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firebase_uid',
        ),
    ]
