# Generated by Django 4.2.20 on 2025-09-12 04:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0019_remove_user_firebase_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_level', models.CharField(choices=[('junior', 'JUNIOR'), ('senior', 'SENIOR'), ('elite', 'ELITE')], max_length=12)),
                ('location', models.CharField(choices=[('domestic', 'DOMESTIC'), ('international', 'INTERNATIONAL')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('duration_weeks', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='admin_functions.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('coach_level', 'location'), name='uniq_plan_category_location'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('category', 'duration_weeks'), name='uniq_plan_category_duration'),
        ),
    ]
