# Generated by Django 4.2.20 on 2025-09-12 12:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0020_category_plan_delete_plans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='coach',
        ),
        migrations.CreateModel(
            name='Clinet_Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_coach', to='admin_functions.clientdetails')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_clients', to='admin_functions.coachprofile')),
            ],
        ),
    ]
