# Generated by Django 4.2.20 on 2025-09-13 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0021_remove_clientdetails_coach_clinet_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinet_coach',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinet_coach',
            name='duration_weeks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActiveClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_client', to='admin_functions.clientdetails')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_clients', to='admin_functions.coachprofile')),
            ],
        ),
    ]
