# Generated by Django 4.2.20 on 2025-09-15 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0022_clinet_coach_active_clinet_coach_duration_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_clients', to='admin_functions.coachprofile'),
        ),
        migrations.AlterField(
            model_name='clinet_coach',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_coach_rel', to='admin_functions.clientdetails'),
        ),
        migrations.AlterField(
            model_name='clinet_coach',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_clients_rel', to='admin_functions.coachprofile'),
        ),
    ]
