# Generated by Django 4.2.20 on 2025-09-15 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0023_clientdetails_coach_alter_clinet_coach_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
