# Generated by Django 4.2.20 on 2025-09-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0024_clientdetails_active_clientdetails_payment_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clinet_coach',
            unique_together={('client', 'coach')},
        ),
    ]
