# Generated by Django 4.2.20 on 2025-09-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0025_alter_clinet_coach_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinet_coach',
            name='inr_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clinet_coach',
            name='us_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
