# Generated by Django 4.2.20 on 2025-09-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0026_clinet_coach_inr_revenue_clinet_coach_us_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inr_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='admin_functions.coachprofile')),
            ],
        ),
    ]
