# Generated by Django 4.2.20 on 2025-09-17 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0027_coachrevenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('temp_password_hashed', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'otp'], name='admin_funct_user_id_323e9f_idx'), models.Index(fields=['expires_at'], name='admin_funct_expires_257fa8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='passwordresetotp',
            constraint=models.UniqueConstraint(condition=models.Q(('used', False)), fields=('user', 'used'), name='unique_active_reset_token_per_user'),
        ),
    ]
