# Generated by Django 4.2.20 on 2025-09-18 05:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0028_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(choices=[('domestic', 'DOMESTIC'), ('international', 'INTERNATIONAL')], max_length=20)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_details', to='admin_functions.clientdetails')),
            ],
        ),
    ]
