# Generated by Django 4.2.20 on 2025-09-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0029_finance_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinet_coach',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
