# Generated by Django 4.2.20 on 2025-09-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0030_alter_clinet_coach_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('soft', 'SOFT'), ('hard', 'HARD')], default='active', max_length=10),
        ),
    ]
