# Generated by Django 4.2.20 on 2025-09-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0032_leads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachprofile',
            old_name='summary',
            new_name='persnol_journey',
        ),
    ]
