# Generated by Django 4.2.20 on 2025-09-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0033_rename_summary_coachprofile_persnol_journey'),
    ]

    operations = [
        migrations.CreateModel(
            name='testImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='test_images/')),
            ],
        ),
    ]
