# Generated by Django 4.2.20 on 2025-09-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0034_testimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachprofile',
            old_name='persnol_journey',
            new_name='summary',
        ),
    ]
