# Generated by Django 4.2.20 on 2025-09-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0035_rename_persnol_journey_coachprofile_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='temp_password_hashed',
        ),
    ]
