# Generated by Django 4.2.20 on 2025-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0036_remove_passwordresetotp_temp_password_hashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin_dp/'),
        ),
    ]
