# Generated by Django 4.2.20 on 2025-09-25 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0039_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachrevenue',
            name='coach',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='admin_functions.coachprofile'),
        ),
    ]
