# Generated by Django 4.2.20 on 2025-09-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0041_enquiryform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnquiryForm',
        ),
    ]
