# Generated by Django 4.2.20 on 2025-09-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0042_delete_enquiryform'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinet_coach',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinet_coach',
            name='location',
            field=models.CharField(choices=[('domestic', 'DOMESTIC'), ('international', 'INTERNATIONAL')], default='domestic', max_length=20),
        ),
    ]
