# Generated by Django 4.2.20 on 2025-09-26 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0043_clinet_coach_end_date_clinet_coach_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
