# Generated by Django 4.2.20 on 2025-10-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0044_alter_clientdetails_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='insta_link',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='linkedin_link',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
