# Generated by Django 4.2.20 on 2025-10-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0045_coachprofile_insta_link_coachprofile_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='base_url',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
