# Generated by Django 4.2.20 on 2025-10-11 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0046_coachprofile_base_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachprofile',
            old_name='base_url',
            new_name='spurfit_url',
        ),
    ]
