# Generated by Django 4.2.20 on 2025-10-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0047_rename_base_url_coachprofile_spurfit_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='experience_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
