# Generated by Django 4.2.20 on 2025-10-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0048_coachprofile_experience_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='experience',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
