# Generated by Django 4.2.20 on 2025-10-25 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0049_alter_coachprofile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
