# Generated by Django 4.2.20 on 2025-12-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0050_alter_clientdetails_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance_details',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
