# Generated by Django 4.2.20 on 2025-12-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0051_finance_details_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
