# Generated by Django 4.2.20 on 2025-12-27 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0052_clientdetails_city_clientdetails_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance_details',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_details', to='admin_functions.coachprofile'),
        ),
        migrations.AddField(
            model_name='finance_details',
            name='plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
