# Generated by Django 4.2.20 on 2025-12-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0053_finance_details_coach_finance_details_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance_details',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
