# Generated by Django 4.2.20 on 2025-12-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_functions', '0054_finance_details_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance_details',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
